(function(){
var base=new File($.fileName).parent.fsName.replace(/\\/g,'/')+'/';
function read(n){var f=new File(base+n);f.encoding='UTF-8';f.open('r');var r=eval('('+f.read()+')');f.close();return r;}
function write(n,s){var f=new File(base+n);f.encoding='UTF-8';f.open('w');f.write(s);f.close();}
var rows=[];
try{var m=read('TASK_032_MASTER.json'),v=read('TASK_032_MASTER_VALIDATION.json'),r=m.color_safety_revision;if(v.status!=='PASS'||v.revision!==3)throw Error('No R03 PASS');if(app.project.path!==new File(m.output_project).fsName)throw Error('Wrong project');var seq;for(var i=0;i<app.project.sequences.numSequences;i++)if(app.project.sequences[i].name===m.output_sequence)seq=app.project.sequences[i];app.project.openSequence(seq.sequenceID);app.enableQE();qe.project.getActiveSequence().player.stop();
var mapping={temperature:'Temperature',tint:'Tint',saturation:'Saturation',exposure:'Exposure',contrast:'Contrast',highlights:'Highlights',shadows:'Shadows',whites:'Whites',blacks:'Blacks',sharpen:'Sharpen',vibrance:'Vibrance',vignette:'Amount'};
for(var o=0;o<r.operations.length;o++){var op=r.operations[o],found=[],clips=seq.videoTracks[op.track].clips;for(i=0;i<clips.numItems;i++)if(Number(clips[i].start.ticks)===op.output_in*10160640000)found.push(clips[i]);if(found.length!==1)throw Error('Ambiguous clip');var lum=null;for(i=0;i<found[0].components.numItems;i++)if(found[0].components[i].displayName==='Lumetri Color'){if(lum)throw Error('Duplicate Lumetri');lum=found[0].components[i];}if(!lum)throw Error('Missing Lumetri');for(var key in op.after)if(op.after.hasOwnProperty(key)){var pr=null;for(i=0;i<lum.properties.numItems;i++)if(lum.properties[i].displayName===mapping[key]){pr=lum.properties[i];break;}if(!pr)throw Error('Missing property '+key);var before=pr.getValue();if(Math.abs(before-op.before[key])>.0001)throw Error('Precondition '+key);pr.setValue(op.after[key],true);if(Math.abs(pr.getValue()-op.after[key])>.0001)throw Error('Postcondition '+key);rows.push(op.source_clip_id+' | '+key+' | '+before+' -> '+pr.getValue());}}
app.project.save();write('TASK_032_REVISION_03_APPLY_LOG.txt','PASS\n'+rows.join('\n'));var path=new File(r.preview_staging);if(path.exists)throw Error('Staging exists');write('TASK_032_REVISION_03_EXPORT_STATUS.txt','STARTED');var result=seq.exportAsMediaDirect(path.fsName,new File(base+'TASK_032_H264_640_360_25.epr').fsName,0);write('TASK_032_REVISION_03_EXPORT_STATUS.txt','RETURN '+result+'; exists '+path.exists);seq.setPlayerPosition('0');
}catch(e){write('TASK_032_REVISION_03_ERROR.txt',String(e)+' line '+e.line);}
})();
