(function(){
var base=new File($.fileName).parent.fsName.replace(/\\/g,'/')+'/';
function read(n){var f=new File(base+n);f.encoding='UTF-8';f.open('r');var r=eval('('+f.read()+')');f.close();return r;}
function write(n,s){var f=new File(base+n);f.encoding='UTF-8';f.open('w');f.write(s);f.close();}
function esc(s){return String(s).replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/[\x00-\x1f]/g,function(c){return '\\u'+('0000'+c.charCodeAt(0).toString(16)).slice(-4);});}
function json(x){if(x===null||typeof x==='undefined')return 'null';if(typeof x==='string')return '"'+esc(x)+'"';if(typeof x==='number'||typeof x==='boolean')return String(x);var a=[],k;if(x instanceof Array){for(k=0;k<x.length;k++)a.push(json(x[k]));return '['+a.join(',')+']';}for(k in x)if(x.hasOwnProperty(k))a.push(json(k)+':'+json(x[k]));return '{'+a.join(',')+'}';}
try{
var m=read('TASK_032_MASTER.json'),command=read('TASK_032_NATIVE_QA_COMMAND.json');if(app.project.path!==new File(m.output_project).fsName)throw Error('Wrong project '+app.project.path);
var seq,logs=[];for(var s=0;s<app.project.sequences.numSequences;s++){var sq=app.project.sequences[s];if(sq.name===m.output_sequence)seq=sq;if(sq.name!==m.output_sequence&&sq.name!==m.background_sequence.output)continue;
for(var kind=0;kind<2;kind++){var tracks=kind?sq.audioTracks:sq.videoTracks;for(var t=0;t<tracks.numTracks;t++)for(var i=0;i<tracks[t].clips.numItems;i++){var c=tracks[t].clips[i],cs=[],media=c.projectItem.getMediaPath(),exists=media?new File(media).exists:null;for(var j=0;j<c.components.numItems;j++){var co=c.components[j],coLog={name:co.displayName,matchName:co.matchName,parameters:[]};var wanted=['Position','Scale','Rotation','Blurriness','Repeat Edge Pixels','Map Black To','Map White To','Amount to Tint','Ignore Alpha','Temperature','Saturation','Exposure','Contrast','Highlights','Shadows','Maximum Amplitude','Input Boost','Look-Ahead Time','Release Time','Limit True Peak'];for(var p=0;p<co.properties.numItems;p++){var pr=co.properties[p];for(var n=0;n<wanted.length;n++)if(pr.displayName===wanted[n]){var d={name:pr.displayName};try{d.value=pr.getValue();d.animated=pr.isTimeVarying();if(d.animated){var keys=pr.getKeys();d.keys=[];for(var k=0;k<keys.length;k++)d.keys.push({ticks:keys[k].ticks,value:pr.getValueAtTime(keys[k])});}}catch(e){d.error=String(e);}coLog.parameters.push(d);break;}}cs.push(coLog);}logs.push({sequence:sq.name,audio:kind===1,track:t,name:c.name,start:c.start.ticks,end:c.end.ticks,inPoint:c.inPoint.ticks,outPoint:c.outPoint.ticks,media:media,media_exists:exists,offline:c.projectItem.isOffline(),components:cs});}}}
if(!seq)throw Error('Sequence missing');app.project.openSequence(seq.sequenceID);app.enableQE();
if(command.action==='start_playback'){seq.setPlayerPosition('0');write('TASK_032_NATIVE_REOPEN_READBACK.json',json({status:'PASS',project:app.project.path,version:app.version,sequence:seq.name,end:seq.end,clips:logs}));qe.project.getActiveSequence().player.play(1);write('TASK_032_NATIVE_PLAYBACK_START.json',json({time:new Date().toString(),ticks:seq.getPlayerPosition().ticks}));}
else {write('TASK_032_NATIVE_PLAYBACK_POSITION.json',json({time:new Date().toString(),ticks:seq.getPlayerPosition().ticks,sequence:seq.name}));if(command.action==='finish_playback'){qe.project.getActiveSequence().player.stop();seq.setPlayerPosition('0');}}
}catch(e){write('TASK_032_NATIVE_QA_ERROR.txt',String(e)+' line '+e.line);}
})();
