from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from models.video_sequence import PremiereSequenceClip
from utils.premiere_project import PREMIERE_TICKS_PER_SECOND, parse_premiere_project_sequence_visual_clips


@dataclass(frozen=True)
class PremiereTransitionScriptJob:
    index: int
    previous_clip_name: str
    next_clip_name: str
    previous_source_path: str
    next_source_path: str
    previous_track_item_id: str
    next_track_item_id: str
    edit_seconds: float
    duration_seconds: float
    transition_name: str = "Cross Dissolve"
    fallback_transition_name: str = "Cross Dissolve"
    transition_reason: str = ""

    def to_javascript_payload(self) -> dict[str, object]:
        return {
            "index": self.index,
            "previousClipName": self.previous_clip_name,
            "nextClipName": self.next_clip_name,
            "previousSourcePath": self.previous_source_path,
            "nextSourcePath": self.next_source_path,
            "previousTrackItemId": self.previous_track_item_id,
            "nextTrackItemId": self.next_track_item_id,
            "editSeconds": round(self.edit_seconds, 3),
            "durationSeconds": round(self.duration_seconds, 3),
            "transitionName": self.transition_name,
            "fallbackTransitionName": self.fallback_transition_name,
            "transitionReason": self.transition_reason,
        }


def build_transition_script_jobs(
    clips: list[PremiereSequenceClip],
    *,
    duration_seconds: float = 1.0,
    transition_name: str = "Cross Dissolve",
    transition_plans: list[dict[str, object]] | None = None,
) -> list[PremiereTransitionScriptJob]:
    ordered_clips = sorted(clips, key=lambda clip: (clip.start, clip.track_index, clip.order_index))
    jobs: list[PremiereTransitionScriptJob] = []
    for index, (previous_clip, next_clip) in enumerate(zip(ordered_clips, ordered_clips[1:]), start=1):
        transition_plan = _transition_plan_at(transition_plans, index - 1)
        planned_transition_name = _clean_transition_name(
            transition_plan.get("transition_name") if transition_plan else None,
            fallback=transition_name,
        )
        planned_duration_seconds = _transition_duration_seconds(
            transition_plan.get("recommended_duration") if transition_plan else None,
            fallback=duration_seconds,
        )
        transition_reason = str(transition_plan.get("reason") or "") if transition_plan else ""
        edit_ticks = previous_clip.end
        if next_clip.start and abs(next_clip.start - previous_clip.end) > PREMIERE_TICKS_PER_SECOND:
            edit_ticks = next_clip.start
        jobs.append(
            PremiereTransitionScriptJob(
                index=index,
                previous_clip_name=previous_clip.name,
                next_clip_name=next_clip.name,
                previous_source_path=previous_clip.source_path,
                next_source_path=next_clip.source_path,
                previous_track_item_id=previous_clip.clipitem_id,
                next_track_item_id=next_clip.clipitem_id,
                edit_seconds=edit_ticks / PREMIERE_TICKS_PER_SECOND,
                duration_seconds=planned_duration_seconds,
                transition_name=planned_transition_name,
                fallback_transition_name=transition_name,
                transition_reason=transition_reason,
            )
        )
    return jobs


def build_premiere_transition_extendscript(
    *,
    sequence_name: str,
    jobs: list[PremiereTransitionScriptJob],
    transition_name: str = "Cross Dissolve",
    video_track_index: int = 0,
    log_path: Path | None = None,
    save_project: bool = True,
) -> str:
    log_path_text = _to_js_path(log_path) if log_path is not None else ""
    payload = [job.to_javascript_payload() for job in jobs]
    return f"""// Generated by img-style-ag_1.
// Open the Premiere project, make sequence {json.dumps(sequence_name, ensure_ascii=False)} active,
// then run this file from Premiere/ExtendScript. The script uses Premiere's QE DOM.

(function () {{
    var EXPECTED_SEQUENCE_NAME = {json.dumps(sequence_name, ensure_ascii=False)};
    var VIDEO_TRACK_INDEX = {int(video_track_index)};
    var FALLBACK_TRANSITION_NAME = {json.dumps(transition_name, ensure_ascii=False)};
    var SAVE_PROJECT = {str(bool(save_project)).lower()};
    var LOG_PATH = {json.dumps(log_path_text, ensure_ascii=False)};
    var TRANSITION_JOBS = {json.dumps(payload, ensure_ascii=False, indent=4)};

    var logFile = null;

    function openLog() {{
        if (!LOG_PATH) {{
            return;
        }}
        try {{
            logFile = new File(LOG_PATH);
            var parent = logFile.parent;
            if (parent && !parent.exists) {{
                parent.create();
            }}
            logFile.open("w");
        }} catch (err) {{
            logFile = null;
        }}
    }}

    function log(message) {{
        var text = "[" + new Date().toUTCString() + "] " + message;
        try {{
            $.writeln(text);
        }} catch (err) {{
        }}
        if (logFile) {{
            try {{
                logFile.writeln(text);
                logFile.flush();
            }} catch (err2) {{
            }}
        }}
    }}

    function closeLog() {{
        if (logFile) {{
            try {{
                logFile.close();
            }} catch (err) {{
            }}
        }}
    }}

    function asText(value) {{
        try {{
            if (value === null || value === undefined) {{
                return "";
            }}
            return String(value);
        }} catch (err) {{
            return "";
        }}
    }}

    function getName(obj) {{
        if (!obj) {{
            return "";
        }}
        try {{
            if (obj.name !== undefined) {{
                return asText(obj.name);
            }}
        }} catch (err) {{
        }}
        try {{
            if (typeof obj.getName === "function") {{
                return asText(obj.getName());
            }}
        }} catch (err2) {{
        }}
        return "";
    }}

    function getMethodNames(obj) {{
        var names = [];
        try {{
            var methods = obj.reflect.methods;
            for (var i = 0; i < methods.length; i += 1) {{
                names.push(asText(methods[i].name || methods[i]));
            }}
        }} catch (err) {{
        }}
        return names.join(", ");
    }}

    function durationTimecodes(seconds) {{
        var fps = 25;
        var totalFrames = Math.max(1, Math.round(seconds * fps));
        var frame = totalFrames % fps;
        var totalSeconds = Math.floor(totalFrames / fps);
        var second = totalSeconds % 60;
        var totalMinutes = Math.floor(totalSeconds / 60);
        var minute = totalMinutes % 60;
        var hour = Math.floor(totalMinutes / 60);
        function pad2(value) {{
            return value < 10 ? "0" + value : String(value);
        }}
        var colon = pad2(hour) + ":" + pad2(minute) + ":" + pad2(second) + ":" + pad2(frame);
        var semicolon = pad2(hour) + ";" + pad2(minute) + ";" + pad2(second) + ";" + pad2(frame);
        return [colon, semicolon, String(seconds)];
    }}

    function tryAddTransition(qeClip, transition, job) {{
        if (!qeClip) {{
            return false;
        }}
        var durations = durationTimecodes(job.durationSeconds);
        var attempts = [];
        for (var i = 0; i < durations.length; i += 1) {{
            (function (durationText) {{
                attempts.push({{
                    label: "addTransition(transition, true, " + durationText + ")",
                    run: function () {{
                        return qeClip.addTransition(transition, true, durationText);
                    }}
                }});
                attempts.push({{
                    label: "addTransition(transition, false, " + durationText + ")",
                    run: function () {{
                        return qeClip.addTransition(transition, false, durationText);
                    }}
                }});
            }}(durations[i]));
        }}
        attempts.push({{
            label: "addTransition(transition)",
            run: function () {{
                return qeClip.addTransition(transition);
            }}
        }});

        for (var attemptIndex = 0; attemptIndex < attempts.length; attemptIndex += 1) {{
            try {{
                attempts[attemptIndex].run();
                log("OK transition " + job.index + " via " + attempts[attemptIndex].label);
                return true;
            }} catch (err) {{
                log("FAILED transition " + job.index + " via " + attempts[attemptIndex].label + ": " + err);
            }}
        }}
        return false;
    }}

    function findVideoTransition(qeProject, requestedName, fallbackName) {{
        var names = [];
        addTransitionNameCandidate(names, requestedName);
        addTransitionNameCandidate(names, removeLegacySuffix(requestedName));
        addTransitionNameCandidate(names, fallbackName);
        addTransitionNameCandidate(names, removeLegacySuffix(fallbackName));
        addTransitionNameCandidate(names, FALLBACK_TRANSITION_NAME);
        addTransitionNameCandidate(names, removeLegacySuffix(FALLBACK_TRANSITION_NAME));
        addTransitionNameCandidate(names, "Cross Dissolve");

        for (var i = 0; i < names.length; i += 1) {{
            try {{
                var transition = qeProject.getVideoTransitionByName(names[i]);
                if (transition) {{
                    if (names[i] !== requestedName) {{
                        log("Using fallback transition '" + names[i] + "' for requested '" + requestedName + "'.");
                    }}
                    return transition;
                }}
            }} catch (err) {{
                log("Transition lookup failed for '" + names[i] + "': " + err);
            }}
        }}
        return null;
    }}

    function addTransitionNameCandidate(names, name) {{
        name = asText(name).replace(/^\\s+|\\s+$/g, "");
        if (!name) {{
            return;
        }}
        for (var i = 0; i < names.length; i += 1) {{
            if (names[i] === name) {{
                return;
            }}
        }}
        names.push(name);
    }}

    function removeLegacySuffix(name) {{
        return asText(name).replace(/\\s*\\(Legacy\\)\\s*$/, "");
    }}

    function main() {{
        openLog();
        log("Premiere transition apply script started.");
        log("Expected sequence: " + EXPECTED_SEQUENCE_NAME);
        log("Fallback transition: " + FALLBACK_TRANSITION_NAME);
        log("Jobs: " + TRANSITION_JOBS.length);

        if (typeof app === "undefined" || !app.enableQE) {{
            throw new Error("Premiere ExtendScript app.enableQE() is not available.");
        }}

        app.enableQE();
        var qeProject = qe.project;
        var qeSequence = qeProject.getActiveSequence();
        if (!qeSequence) {{
            throw new Error("No active QE sequence. Open the target sequence in Premiere before running the script.");
        }}

        var activeName = getName(qeSequence);
        log("Active QE sequence: " + activeName);
        if (activeName !== EXPECTED_SEQUENCE_NAME) {{
            throw new Error("Active sequence is '" + activeName + "', expected '" + EXPECTED_SEQUENCE_NAME + "'.");
        }}

        var qeTrack = qeSequence.getVideoTrackAt(VIDEO_TRACK_INDEX);
        if (!qeTrack) {{
            throw new Error("Could not access video track index " + VIDEO_TRACK_INDEX + ".");
        }}
        log("Video track methods: " + getMethodNames(qeTrack));
        try {{
            log("Video track item count: " + qeTrack.numItems);
        }} catch (countErr) {{
        }}

        var applied = 0;
        for (var jobIndex = 0; jobIndex < TRANSITION_JOBS.length; jobIndex += 1) {{
            var job = TRANSITION_JOBS[jobIndex];
            var clipIndex = job.index - 1;
            var qeClip = null;
            try {{
                qeClip = qeTrack.getItemAt(clipIndex);
            }} catch (clipErr) {{
                log("FAILED to get item at index " + clipIndex + ": " + clipErr);
                continue;
            }}
            log(
                "Applying transition " + job.index +
                " at " + job.editSeconds + "s: " +
                job.previousClipName + " -> " + job.nextClipName +
                "; requested='" + job.transitionName + "'" +
                "; QE item name='" + getName(qeClip) + "'"
            );
            if (job.transitionReason) {{
                log("Transition reason " + job.index + ": " + job.transitionReason);
            }}
            log("QE clip methods: " + getMethodNames(qeClip));
            var transition = findVideoTransition(qeProject, job.transitionName, job.fallbackTransitionName || FALLBACK_TRANSITION_NAME);
            if (!transition) {{
                log("FAILED transition " + job.index + ": no requested or fallback transition was found.");
                continue;
            }}
            if (tryAddTransition(qeClip, transition, job)) {{
                applied += 1;
            }}
        }}

        log("Applied transitions: " + applied + " / " + TRANSITION_JOBS.length);
        if (SAVE_PROJECT) {{
            try {{
                app.project.save();
                log("Project saved.");
            }} catch (saveErr) {{
                log("Project save failed: " + saveErr);
            }}
        }}
        alert("Transition script finished. Applied " + applied + " of " + TRANSITION_JOBS.length + " transitions. Log: " + LOG_PATH);
    }}

    try {{
        main();
    }} catch (err) {{
        log("FATAL: " + err);
        alert("Transition script failed: " + err + "\\nLog: " + LOG_PATH);
    }} finally {{
        closeLog();
    }}
}}());
"""


def write_premiere_transition_extendscript(
    *,
    project_path: Path,
    sequence_name: str,
    output_jsx_path: Path,
    transition_name: str = "Cross Dissolve",
    duration_seconds: float = 1.0,
    video_track_index: int = 0,
    save_project: bool = True,
    optimization_report_json: Path | None = None,
) -> tuple[Path, list[PremiereTransitionScriptJob]]:
    selected_sequence_name, clips = parse_premiere_project_sequence_visual_clips(project_path, sequence_name)
    transition_plans = _load_transition_plans(optimization_report_json)
    jobs = build_transition_script_jobs(
        clips,
        duration_seconds=duration_seconds,
        transition_name=transition_name,
        transition_plans=transition_plans,
    )
    log_path = output_jsx_path.with_suffix(".log")
    script = build_premiere_transition_extendscript(
        sequence_name=selected_sequence_name,
        jobs=jobs,
        transition_name=transition_name,
        video_track_index=video_track_index,
        log_path=log_path,
        save_project=save_project,
    )
    output_jsx_path.parent.mkdir(parents=True, exist_ok=True)
    output_jsx_path.write_text(script, encoding="utf-8")
    return output_jsx_path, jobs


def _load_transition_plans(path: Path | None) -> list[dict[str, object]] | None:
    if path is None or not path.exists():
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    plans: list[dict[str, object]] = []
    for entry in payload.get("entries") or []:
        if not isinstance(entry, dict):
            continue
        transition_plan = entry.get("transition_to_next")
        if isinstance(transition_plan, dict):
            plans.append(transition_plan)
    return plans


def _transition_plan_at(plans: list[dict[str, object]] | None, index: int) -> dict[str, object] | None:
    if not plans or index < 0 or index >= len(plans):
        return None
    return plans[index]


def _clean_transition_name(value: object, *, fallback: str) -> str:
    text = str(value or "").strip()
    return text or fallback


def _transition_duration_seconds(value: object, *, fallback: float) -> float:
    try:
        raw = float(value)
    except (TypeError, ValueError):
        return fallback
    if raw <= 0:
        return fallback
    if raw > 1000:
        return max(0.25, raw / PREMIERE_TICKS_PER_SECOND)
    return max(0.25, raw)


def _to_js_path(path: Path) -> str:
    return str(path).replace("\\", "/")
