from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from models.video_sequence import PremiereSequenceClip
from utils.premiere_project import (
    PREMIERE_TICKS_PER_SECOND,
    is_supported_image_media_path,
    parse_premiere_project_sequence_visual_clips,
)


@dataclass(frozen=True)
class PremiereTransformScriptJob:
    index: int
    clip_index: int
    clip_name: str
    source_path: str
    track_item_id: str
    start_seconds: float
    end_seconds: float
    transform_key: str
    effect_name: str
    fallback_effect_name: str
    start_scale: float
    end_scale: float
    transform_reason: str = ""

    def to_javascript_payload(self) -> dict[str, object]:
        return {
            "index": self.index,
            "clipIndex": self.clip_index,
            "clipName": self.clip_name,
            "sourcePath": self.source_path,
            "trackItemId": self.track_item_id,
            "startSeconds": round(self.start_seconds, 3),
            "endSeconds": round(self.end_seconds, 3),
            "transformKey": self.transform_key,
            "effectName": self.effect_name,
            "fallbackEffectName": self.fallback_effect_name,
            "startScale": round(self.start_scale, 3),
            "endScale": round(self.end_scale, 3),
            "transformReason": self.transform_reason,
        }


def build_transform_script_jobs(
    clips: list[PremiereSequenceClip],
    *,
    transform_plans: list[dict[str, object] | None] | None = None,
    default_effect_name: str = "Transform",
) -> list[PremiereTransformScriptJob]:
    ordered_clips = sorted(clips, key=lambda clip: (clip.start, clip.track_index, clip.order_index))
    jobs: list[PremiereTransformScriptJob] = []
    for clip_index, clip in enumerate(ordered_clips):
        plan = _transform_plan_at(transform_plans, clip_index)
        if plan is None:
            if not is_supported_image_media_path(clip.source_path or clip.name):
                continue
            plan = _default_transform_plan(default_effect_name)
        elif str(plan.get("media_kind") or "").casefold() != "image":
            continue

        effect_name = _clean_effect_name(plan.get("effect_name"), fallback=default_effect_name)
        fallback_effect_name = _clean_effect_name(plan.get("fallback_effect_name"), fallback="Transform")
        jobs.append(
            PremiereTransformScriptJob(
                index=len(jobs) + 1,
                clip_index=clip_index,
                clip_name=clip.name,
                source_path=clip.source_path,
                track_item_id=clip.clipitem_id,
                start_seconds=clip.start / PREMIERE_TICKS_PER_SECOND,
                end_seconds=clip.end / PREMIERE_TICKS_PER_SECOND,
                transform_key=str(plan.get("transform_key") or "transform"),
                effect_name=effect_name,
                fallback_effect_name=fallback_effect_name,
                start_scale=_float_value(plan.get("start_scale"), fallback=100.0),
                end_scale=_float_value(plan.get("end_scale"), fallback=105.0),
                transform_reason=str(plan.get("reason") or ""),
            )
        )
    return jobs


def build_premiere_transform_extendscript(
    *,
    sequence_name: str,
    jobs: list[PremiereTransformScriptJob],
    video_track_index: int = 0,
    log_path: Path | None = None,
    save_project: bool = True,
    add_video_effects: bool = False,
    apply_safe_transform_effect: bool = True,
) -> str:
    log_path_text = _to_js_path(log_path) if log_path is not None else ""
    payload = [job.to_javascript_payload() for job in jobs]
    return f"""// Generated by img-style-ag_1.
// Open the Premiere project, make sequence {json.dumps(sequence_name, ensure_ascii=False)} active,
// then run this file from Premiere/ExtendScript. When ADD_VIDEO_EFFECTS is enabled,
// it applies the requested Premiere effects from the Transform group, such as
// Grow/Shrink/Move, and does not touch intrinsic Motion / Scale. Offset is kept
// manual-only because it often needs frame-by-frame composition tuning. The plain
// Transform scale-keyframe fallback is only used when ADD_VIDEO_EFFECTS is disabled
// and APPLY_SAFE_TRANSFORM_EFFECT is enabled.

(function () {{
    var EXPECTED_SEQUENCE_NAME = {json.dumps(sequence_name, ensure_ascii=False)};
    var VIDEO_TRACK_INDEX = {int(video_track_index)};
    var SAVE_PROJECT = {str(bool(save_project)).lower()};
    var ADD_VIDEO_EFFECTS = {str(bool(add_video_effects)).lower()};
    var APPLY_SAFE_TRANSFORM_EFFECT = {str(bool(apply_safe_transform_effect)).lower()};
    var LOG_PATH = {json.dumps(log_path_text, ensure_ascii=False)};
    var TICKS_PER_SECOND = {PREMIERE_TICKS_PER_SECOND};
    var KEYFRAME_SEQUENCE_OFFSET_SECONDS = 3600.0;
    var TRANSFORM_JOBS = {json.dumps(payload, ensure_ascii=False, indent=4)};

    var logFile = null;

    function openLog() {{
        if (!LOG_PATH) {{
            return;
        }}
        try {{
            logFile = new File(LOG_PATH);
            var parent = logFile.parent;
            if (parent && !parent.exists) {{
                parent.create();
            }}
            logFile.open("w");
        }} catch (err) {{
            logFile = null;
        }}
    }}

    function log(message) {{
        var text = "[" + new Date().toUTCString() + "] " + message;
        try {{
            $.writeln(text);
        }} catch (err) {{
        }}
        if (logFile) {{
            try {{
                logFile.writeln(text);
                logFile.flush();
            }} catch (err2) {{
            }}
        }}
    }}

    function closeLog() {{
        if (logFile) {{
            try {{
                logFile.close();
            }} catch (err) {{
            }}
        }}
    }}

    function asText(value) {{
        try {{
            if (value === null || value === undefined) {{
                return "";
            }}
            return String(value);
        }} catch (err) {{
            return "";
        }}
    }}

    function getName(obj) {{
        if (!obj) {{
            return "";
        }}
        try {{
            if (obj.name !== undefined) {{
                return asText(obj.name);
            }}
        }} catch (err) {{
        }}
        try {{
            if (obj.displayName !== undefined) {{
                return asText(obj.displayName);
            }}
        }} catch (err2) {{
        }}
        try {{
            if (typeof obj.getName === "function") {{
                return asText(obj.getName());
            }}
        }} catch (err3) {{
        }}
        return "";
    }}

    function getCollectionLength(collection) {{
        if (!collection) {{
            return 0;
        }}
        try {{
            if (collection.numItems !== undefined) {{
                return Number(collection.numItems);
            }}
        }} catch (err) {{
        }}
        try {{
            if (collection.length !== undefined) {{
                return Number(collection.length);
            }}
        }} catch (err2) {{
        }}
        return 0;
    }}

    function getCollectionItem(collection, index) {{
        if (!collection) {{
            return null;
        }}
        try {{
            return collection[index];
        }} catch (err) {{
        }}
        try {{
            if (typeof collection.getItemAt === "function") {{
                return collection.getItemAt(index);
            }}
        }} catch (err2) {{
        }}
        return null;
    }}

    function addNameCandidate(names, name) {{
        name = asText(name).replace(/^\\s+|\\s+$/g, "");
        if (!name) {{
            return;
        }}
        for (var i = 0; i < names.length; i += 1) {{
            if (names[i] === name) {{
                return;
            }}
        }}
        names.push(name);
    }}

    function findVideoEffect(qeProject, requestedName, fallbackName) {{
        var names = [];
        addNameCandidate(names, requestedName);
        addNameCandidate(names, fallbackName);
        addNameCandidate(names, "Transform");
        addNameCandidate(names, "Grow");
        addNameCandidate(names, "Shrink");
        addNameCandidate(names, "Move");
        addNameCandidate(names, "Offset");

        for (var i = 0; i < names.length; i += 1) {{
            try {{
                var effect = qeProject.getVideoEffectByName(names[i]);
                if (effect) {{
                    if (names[i] !== requestedName) {{
                        log("Using fallback video effect '" + names[i] + "' for requested '" + requestedName + "'.");
                    }}
                    return effect;
                }}
            }} catch (err) {{
                log("Video effect lookup failed for '" + names[i] + "': " + err);
            }}
        }}
        return null;
    }}

    function secondsOf(timeObj) {{
        try {{
            if (timeObj && timeObj.seconds !== undefined) {{
                return Number(timeObj.seconds);
            }}
        }} catch (err) {{
        }}
        try {{
            if (timeObj && timeObj.ticks !== undefined) {{
                return Number(timeObj.ticks) / TICKS_PER_SECOND;
            }}
        }} catch (err2) {{
        }}
        return 0;
    }}

    function makeTime(seconds) {{
        var time = new Time();
        seconds = Math.max(0, Number(seconds));
        try {{
            time.setSecondsAsFraction(Math.round(seconds * 1000), 1000);
            return time;
        }} catch (fractionErr) {{
            log("setSecondsAsFraction failed for " + seconds + "s: " + fractionErr);
        }}
        time.ticks = String(Math.max(0, Math.round(seconds * TICKS_PER_SECOND)));
        return time;
    }}

    function addEffectToQeClip(qeClip, qeProject, job) {{
        if (!qeClip) {{
            return false;
        }}
        var effect = findVideoEffect(qeProject, job.effectName, job.fallbackEffectName);
        if (!effect) {{
            log("FAILED transform " + job.index + ": no requested or fallback effect was found.");
            return false;
        }}
        try {{
            qeClip.addVideoEffect(effect);
            log("OK transform " + job.index + ": added effect '" + job.effectName + "'.");
            return true;
        }} catch (err) {{
            log("FAILED transform " + job.index + ": addVideoEffect failed: " + err);
            return false;
        }}
    }}

    function addPlainTransformEffectToQeClip(qeClip, qeProject, job) {{
        if (!qeClip) {{
            return false;
        }}
        var effect = findVideoEffect(qeProject, "Transform", "Transform");
        if (!effect) {{
            log("FAILED transform " + job.index + ": plain Transform effect was not found.");
            return false;
        }}
        try {{
            qeClip.addVideoEffect(effect);
            log("OK transform " + job.index + ": added plain Transform effect for keyframes.");
            return true;
        }} catch (err) {{
            log("FAILED transform " + job.index + ": add plain Transform failed: " + err);
            return false;
        }}
    }}

    function findScaleParams(publicClip, preferTransformEffect) {{
        var components = publicClip ? publicClip.components : null;
        var componentCount = getCollectionLength(components);
        var transformParams = [];
        var fallbackParams = [];
        for (var componentIndex = 0; componentIndex < componentCount; componentIndex += 1) {{
            var component = getCollectionItem(components, componentIndex);
            if (!component) {{
                continue;
            }}
            var componentName = getName(component).toLowerCase();
            var componentLabel = getName(component);
            var properties = component.properties;
            var propertyCount = getCollectionLength(properties);
            var transformScaleParams = [];
            for (var propertyIndex = 0; propertyIndex < propertyCount; propertyIndex += 1) {{
                var property = getCollectionItem(properties, propertyIndex);
                var propertyName = getName(property);
                var search = (
                    componentLabel + " " +
                    propertyName + " " +
                    asText(property ? property.matchName : "")
                ).toLowerCase();
                var isScale = search.indexOf("scale") >= 0 || search.indexOf("масштаб") >= 0;
                var isUniformCheckbox = search.indexOf("uniform") >= 0 || search.indexOf("checkbox") >= 0;
                var isTransformComponent =
                    componentName.indexOf("transform") >= 0 &&
                    componentName.indexOf("motion") < 0;
                if (isScale && !isUniformCheckbox) {{
                    var item = {{
                        param: property,
                        label: componentLabel + " / " + propertyName,
                        componentLabel: componentLabel
                    }};
                    if (preferTransformEffect && isTransformComponent) {{
                        transformScaleParams.push(item);
                    }} else if (fallbackParams.length === 0) {{
                        fallbackParams.push(item);
                    }}
                }}
            }}
            if (transformScaleParams.length > 0) {{
                log("Found " + transformScaleParams.length + " Scale parameter(s) from component '" + componentLabel + "'.");
                transformParams = transformParams.concat(transformScaleParams);
            }}
        }}
        if (transformParams.length > 0) {{
            log("Using " + transformParams.length + " Scale parameter(s) from plain Transform component(s).");
            return transformParams;
        }}
        if (fallbackParams.length > 0) {{
            log("Using fallback Scale parameter(s) outside plain Transform effect.");
        }}
        return fallbackParams;
    }}

    function applyOneScaleParam(paramItem, job, startTime, endTime) {{
        var scaleParam = paramItem.param;
        var label = paramItem.label || "Scale";
        logParamCapabilities(scaleParam, job, label);
        if (!trySetTimeVarying(scaleParam)) {{
            log("FAILED transform " + job.index + " on " + label + ": parameter did not become time-varying.");
        }}
        var keysBefore = countKeys(scaleParam);
        log("Transform " + job.index + " on " + label + ": keys before add = " + keysBefore + " " + keySummary(scaleParam) + ".");
        tryAddKey(scaleParam, startTime, job, label, "start");
        tryAddKey(scaleParam, endTime, job, label, "end");
        var baseScale = readNumericParamValue(scaleParam, 100);
        var startScale = baseScale * (Number(job.startScale) / 100.0);
        var endScale = baseScale * (Number(job.endScale) / 100.0);
        var startOk = trySetValueAtKey(scaleParam, startTime, startScale);
        var endOk = trySetValueAtKey(scaleParam, endTime, endScale);
        trySetInterpolation(scaleParam, startTime, job, label);
        trySetInterpolation(scaleParam, endTime, job, label);
        var keysAfter = countKeys(scaleParam);
        if (startOk && endOk && keysAfter >= 2) {{
            log("OK transform " + job.index + " on " + label + ": verified keyframes=" + keysAfter + " " + keySummary(scaleParam) + ", relative Scale " + job.startScale + "% -> " + job.endScale + "%, actual " + startScale + " -> " + endScale + ".");
            return true;
        }}
        log("Transform " + job.index + " on " + label + ": setValueAtKey returned start=" + startOk + ", end=" + endOk + ", keys after=" + keysAfter + ". Trying setValueAtTime fallback.");
        var startTimeOk = trySetValueAtTime(scaleParam, startTime, startScale);
        var endTimeOk = trySetValueAtTime(scaleParam, endTime, endScale);
        trySetInterpolation(scaleParam, startTime, job, label);
        trySetInterpolation(scaleParam, endTime, job, label);
        keysAfter = countKeys(scaleParam);
        if (startTimeOk && endTimeOk && keysAfter >= 2) {{
            log("OK transform " + job.index + " on " + label + ": verified keyframes via setValueAtTime=" + keysAfter + " " + keySummary(scaleParam) + ".");
            return true;
        }}
        log("FAILED transform " + job.index + " on " + label + ": keyframes not verified; setValueAtTime returned start=" + startTimeOk + ", end=" + endTimeOk + ", keys after=" + keysAfter + " " + keySummary(scaleParam) + ".");
        try {{
            scaleParam.setValue(endScale, 1);
            log("Fallback transform " + job.index + " on " + label + ": set constant relative Scale " + endScale + ".");
            return false;
        }} catch (setErr) {{
            log("FAILED transform " + job.index + " on " + label + ": constant Scale fallback failed: " + setErr);
        }}
        return false;
    }}

    function tryAddKey(param, time, job, label, keyLabel) {{
        var attempts = [
            {{
                name: "Time object",
                value: time
            }},
            {{
                name: "ticks string",
                value: time ? time.ticks : ""
            }},
            {{
                name: "seconds number",
                value: time ? time.seconds : 0
            }}
        ];
        for (var attemptIndex = 0; attemptIndex < attempts.length; attemptIndex += 1) {{
            try {{
                if (typeof param.addKey === "function") {{
                    param.addKey(attempts[attemptIndex].value);
                    log("addKey " + keyLabel + " OK for transform " + job.index + " on " + label + " via " + attempts[attemptIndex].name + ".");
                    return true;
                }}
            }} catch (keyErr) {{
                log("addKey " + keyLabel + " failed for transform " + job.index + " on " + label + " via " + attempts[attemptIndex].name + ": " + keyErr);
            }}
        }}
        return false;
    }}

    function keySummary(param) {{
        try {{
            if (typeof param.getKeys === "function") {{
                var keys = param.getKeys();
                if (!keys) {{
                    return "[]";
                }}
                var parts = [];
                var length = keys.length !== undefined ? Number(keys.length) : 0;
                for (var i = 0; i < length; i += 1) {{
                    parts.push(timeSummary(keys[i]));
                }}
                return "[" + parts.join(", ") + "]";
            }}
        }} catch (keysErr) {{
            return "[getKeys failed: " + keysErr + "]";
        }}
        return "[getKeys unavailable]";
    }}

    function timeSummary(time) {{
        try {{
            if (time && time.seconds !== undefined) {{
                return Number(time.seconds).toFixed(3) + "s";
            }}
        }} catch (err) {{
        }}
        try {{
            if (time && time.ticks !== undefined) {{
                return String(time.ticks) + "t";
            }}
        }} catch (err2) {{
        }}
        return asText(time);
    }}

    function countKeys(param) {{
        try {{
            if (typeof param.getKeys === "function") {{
                var keys = param.getKeys();
                if (keys === 0 || keys === null || keys === undefined) {{
                    return 0;
                }}
                if (keys.length !== undefined) {{
                    return Number(keys.length);
                }}
            }}
        }} catch (keysErr) {{
            log("getKeys failed: " + keysErr);
        }}
        return 0;
    }}

    function logParamCapabilities(param, job, label) {{
        try {{
            if (typeof param.areKeyframesSupported === "function") {{
                log("Transform " + job.index + " on " + label + ": keyframes supported = " + param.areKeyframesSupported() + ".");
            }}
        }} catch (supportedErr) {{
            log("areKeyframesSupported failed for transform " + job.index + " on " + label + ": " + supportedErr);
        }}
        try {{
            if (typeof param.isTimeVarying === "function") {{
                log("Transform " + job.index + " on " + label + ": time-varying before = " + param.isTimeVarying() + ".");
            }}
        }} catch (varyingErr) {{
            log("isTimeVarying failed for transform " + job.index + " on " + label + ": " + varyingErr);
        }}
    }}

    function trySetInterpolation(param, time, job, label) {{
        try {{
            if (typeof param.setInterpolationTypeAtKey === "function") {{
                param.setInterpolationTypeAtKey(time, 0, 1);
            }}
        }} catch (interpErr) {{
            log("setInterpolationTypeAtKey failed for transform " + job.index + " on " + label + ": " + interpErr);
        }}
    }}

    function findUniformScaleParam(publicClip) {{
        var components = publicClip ? publicClip.components : null;
        var componentCount = getCollectionLength(components);
        for (var componentIndex = 0; componentIndex < componentCount; componentIndex += 1) {{
            var component = getCollectionItem(components, componentIndex);
            if (!component) {{
                continue;
            }}
            var componentName = getName(component).toLowerCase();
            if (componentName.indexOf("transform") < 0 || componentName.indexOf("motion") >= 0) {{
                continue;
            }}
            var properties = component.properties;
            var propertyCount = getCollectionLength(properties);
            for (var propertyIndex = 0; propertyIndex < propertyCount; propertyIndex += 1) {{
                var property = getCollectionItem(properties, propertyIndex);
                var search = (
                    getName(component) + " " +
                    getName(property) + " " +
                    asText(property ? property.matchName : "")
                ).toLowerCase();
                if (search.indexOf("uniform") >= 0 && search.indexOf("scale") >= 0) {{
                    return property;
                }}
            }}
        }}
        return null;
    }}

    function trySetTimeVarying(param) {{
        var ok = false;
        try {{
            if (typeof param.setTimeVarying === "function") {{
                param.setTimeVarying(true);
                ok = true;
            }}
        }} catch (err) {{
            log("setTimeVarying(true) failed: " + err);
        }}
        try {{
            if (typeof param.isTimeVarying === "function") {{
                if (param.isTimeVarying()) {{
                    return true;
                }}
            }}
        }} catch (varyingErr) {{
            log("isTimeVarying check failed after setTimeVarying(true): " + varyingErr);
        }}
        try {{
            if (typeof param.setTimeVarying === "function") {{
                param.setTimeVarying(1);
                ok = true;
            }}
        }} catch (err2) {{
            log("setTimeVarying(1) failed: " + err2);
        }}
        try {{
            if (typeof param.isTimeVarying === "function") {{
                return Boolean(param.isTimeVarying());
            }}
        }} catch (varyingErr2) {{
            log("isTimeVarying check failed after setTimeVarying(1): " + varyingErr2);
        }}
        return ok;
    }}

    function trySetValueAtKey(param, time, value) {{
        try {{
            param.setValueAtKey(time, value, 1);
            return true;
        }} catch (err) {{
            log("setValueAtKey(value,1) failed: " + err);
        }}
        try {{
            param.setValueAtKey(time, value, true);
            return true;
        }} catch (err2) {{
            log("setValueAtKey(value,true) failed: " + err2);
        }}
        try {{
            param.setValueAtKey(time, value);
            return true;
        }} catch (err3) {{
            log("setValueAtKey(value) failed: " + err3);
        }}
        return false;
    }}

    function trySetValueAtTime(param, time, value) {{
        try {{
            if (typeof param.setValueAtTime === "function") {{
                param.setValueAtTime(time, value, 1);
                return true;
            }}
        }} catch (err) {{
            log("setValueAtTime(value,1) failed: " + err);
        }}
        try {{
            if (typeof param.setValueAtTime === "function") {{
                param.setValueAtTime(time, value, true);
                return true;
            }}
        }} catch (err2) {{
            log("setValueAtTime(value,true) failed: " + err2);
        }}
        return false;
    }}

    function applyScaleKeyframes(publicClip, job) {{
        if (!publicClip) {{
            log("No public DOM clip for transform " + job.index + "; scale keyframes cannot be applied.");
            return false;
        }}
        var scaleParams = findScaleParams(publicClip, APPLY_SAFE_TRANSFORM_EFFECT);
        if (!scaleParams || scaleParams.length === 0) {{
            log("No Scale parameter found for transform " + job.index + ".");
            return false;
        }}
        var uniformParam = findUniformScaleParam(publicClip);
        if (uniformParam) {{
            try {{
                uniformParam.setValue(false, 1);
                log("Set Transform Uniform Scale false for transform " + job.index + " so Scale Height/Width keyframes stay visible.");
            }} catch (uniformErr) {{
                log("Could not set Uniform Scale for transform " + job.index + ": " + uniformErr);
            }}
        }}
        var clipStart = secondsOf(publicClip.start);
        var clipEnd = secondsOf(publicClip.end);
        if (clipEnd <= clipStart) {{
            clipStart = Number(job.startSeconds || 0);
            clipEnd = Number(job.endSeconds || clipStart + 1);
        }}
        var clipDuration = Math.max(0.01, clipEnd - clipStart);
        var keyInset = Math.min(0.5, Math.max(0.15, clipDuration * 0.125));
        var localStartSeconds = keyInset;
        var localEndSeconds = Math.max(localStartSeconds + 0.25, clipDuration - keyInset);
        if (localEndSeconds > clipDuration) {{
            localEndSeconds = clipDuration;
        }}
        var startTime = makeTime(KEYFRAME_SEQUENCE_OFFSET_SECONDS + localStartSeconds);
        var endTime = makeTime(KEYFRAME_SEQUENCE_OFFSET_SECONDS + localEndSeconds);
        log(
            "Transform " + job.index +
            ": sequence clip " + clipStart.toFixed(3) + "s-" + clipEnd.toFixed(3) +
            "s, keyframes local " + localStartSeconds.toFixed(3) + "s-" +
            localEndSeconds.toFixed(3) + "s, absolute " +
            (KEYFRAME_SEQUENCE_OFFSET_SECONDS + localStartSeconds).toFixed(3) +
            "s-" +
            (KEYFRAME_SEQUENCE_OFFSET_SECONDS + localEndSeconds).toFixed(3) + "s."
        );
        var okCount = 0;
        for (var scaleIndex = 0; scaleIndex < scaleParams.length; scaleIndex += 1) {{
            if (applyOneScaleParam(scaleParams[scaleIndex], job, startTime, endTime)) {{
                okCount += 1;
            }}
        }}
        return okCount > 0;
    }}

    function readNumericParamValue(param, fallbackValue) {{
        try {{
            if (typeof param.getValue === "function") {{
                var value = param.getValue();
                if (value instanceof Array && value.length > 0) {{
                var firstValue = Number(value[0]);
                return isFinite(firstValue) && firstValue > 0 ? firstValue : Number(fallbackValue);
            }}
                var numericValue = Number(value);
                return isFinite(numericValue) && numericValue > 0 ? numericValue : Number(fallbackValue);
            }}
        }} catch (err) {{
            log("getValue failed, using fallback scale " + fallbackValue + ": " + err);
        }}
        return Number(fallbackValue);
    }}

    function main() {{
        openLog();
        log("Premiere transform apply script started.");
        log("Expected sequence: " + EXPECTED_SEQUENCE_NAME);
        log("Jobs: " + TRANSFORM_JOBS.length);

        if (typeof app === "undefined" || !app.enableQE) {{
            throw new Error("Premiere ExtendScript app.enableQE() is not available.");
        }}

        app.enableQE();
        var qeProject = qe.project;
        var qeSequence = qeProject.getActiveSequence();
        if (!qeSequence) {{
            throw new Error("No active QE sequence. Open the target sequence in Premiere before running the script.");
        }}

        var activeName = getName(qeSequence);
        log("Active QE sequence: " + activeName);
        if (activeName !== EXPECTED_SEQUENCE_NAME) {{
            throw new Error("Active sequence is '" + activeName + "', expected '" + EXPECTED_SEQUENCE_NAME + "'.");
        }}

        var publicSequence = app.project.activeSequence;
        var qeTrack = qeSequence.getVideoTrackAt(VIDEO_TRACK_INDEX);
        if (!qeTrack) {{
            throw new Error("Could not access QE video track index " + VIDEO_TRACK_INDEX + ".");
        }}
        var publicTrack = publicSequence && publicSequence.videoTracks ? getCollectionItem(publicSequence.videoTracks, VIDEO_TRACK_INDEX) : null;
        if (!publicTrack) {{
            log("Public DOM video track index " + VIDEO_TRACK_INDEX + " was not available; effects will still be attempted.");
        }}

        var effectsApplied = 0;
        var scalesApplied = 0;
        for (var jobIndex = 0; jobIndex < TRANSFORM_JOBS.length; jobIndex += 1) {{
            var job = TRANSFORM_JOBS[jobIndex];
            var qeClip = null;
            var publicClip = null;
            try {{
                qeClip = qeTrack.getItemAt(job.clipIndex);
            }} catch (clipErr) {{
                log("FAILED to get QE item at index " + job.clipIndex + ": " + clipErr);
            }}
            try {{
                publicClip = publicTrack && publicTrack.clips ? getCollectionItem(publicTrack.clips, job.clipIndex) : null;
            }} catch (publicClipErr) {{
                log("FAILED to get public clip at index " + job.clipIndex + ": " + publicClipErr);
            }}
            log(
                "Applying transform " + job.index +
                " to clip index " + job.clipIndex +
                ": " + job.clipName +
                "; effect='" + job.effectName + "'" +
                "; key='" + job.transformKey + "'"
            );
            if (job.transformReason) {{
                log("Transform reason " + job.index + ": " + job.transformReason);
            }}
            var usedRequestedVideoEffect = false;
            if (ADD_VIDEO_EFFECTS) {{
                usedRequestedVideoEffect = addEffectToQeClip(qeClip, qeProject, job);
                if (usedRequestedVideoEffect) {{
                    effectsApplied += 1;
                    log("Transform " + job.index + ": requested effect mode is active; skipping intrinsic Motion / Scale keyframes.");
                    continue;
                }}
                log("Transform " + job.index + ": requested effect could not be applied; no Motion / Scale fallback will be used in ADD_VIDEO_EFFECTS mode.");
                continue;
            }}
            if (APPLY_SAFE_TRANSFORM_EFFECT && addPlainTransformEffectToQeClip(qeClip, qeProject, job)) {{
                effectsApplied += 1;
            }}
            if (applyScaleKeyframes(publicClip, job)) {{
                scalesApplied += 1;
            }}
        }}

        log("Applied transform effects: " + effectsApplied + " / " + TRANSFORM_JOBS.length);
        log("Applied scale keyframes: " + scalesApplied + " / " + TRANSFORM_JOBS.length);
        if (SAVE_PROJECT) {{
            try {{
                app.project.save();
                log("Project saved.");
            }} catch (saveErr) {{
                log("Project save failed: " + saveErr);
            }}
        }}
        alert("Transform script finished. Optional effects " + effectsApplied + "/" + TRANSFORM_JOBS.length + ", scale keyframes " + scalesApplied + "/" + TRANSFORM_JOBS.length + ". Log: " + LOG_PATH);
    }}

    try {{
        main();
    }} catch (err) {{
        log("FATAL: " + err);
        alert("Transform script failed: " + err + "\\nLog: " + LOG_PATH);
    }} finally {{
        closeLog();
    }}
}}());
"""


def write_premiere_transform_extendscript(
    *,
    project_path: Path,
    sequence_name: str,
    output_jsx_path: Path,
    video_track_index: int = 0,
    save_project: bool = True,
    optimization_report_json: Path | None = None,
    default_effect_name: str = "Transform",
    add_video_effects: bool = False,
    apply_safe_transform_effect: bool = True,
) -> tuple[Path, list[PremiereTransformScriptJob]]:
    selected_sequence_name, clips = parse_premiere_project_sequence_visual_clips(project_path, sequence_name)
    transform_plans = _load_transform_plans(optimization_report_json)
    jobs = build_transform_script_jobs(
        clips,
        transform_plans=transform_plans,
        default_effect_name=default_effect_name,
    )
    log_path = output_jsx_path.with_suffix(".log")
    script = build_premiere_transform_extendscript(
        sequence_name=selected_sequence_name,
        jobs=jobs,
        video_track_index=video_track_index,
        log_path=log_path,
        save_project=save_project,
        add_video_effects=add_video_effects,
        apply_safe_transform_effect=apply_safe_transform_effect,
    )
    output_jsx_path.parent.mkdir(parents=True, exist_ok=True)
    output_jsx_path.write_text(script, encoding="utf-8")
    return output_jsx_path, jobs


def _load_transform_plans(path: Path | None) -> list[dict[str, object] | None] | None:
    if path is None or not path.exists():
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    plans: list[dict[str, object] | None] = []
    for entry in payload.get("entries") or []:
        if not isinstance(entry, dict):
            plans.append(None)
            continue
        transform_plan = entry.get("transform_plan")
        if isinstance(transform_plan, dict):
            plans.append(transform_plan)
        else:
            plans.append(_derive_transform_plan_from_report_entry(entry, entry_index=len(plans)))
    return plans


def _transform_plan_at(
    plans: list[dict[str, object] | None] | None,
    index: int,
) -> dict[str, object] | None:
    if not plans or index < 0 or index >= len(plans):
        return None
    return plans[index]


def _default_transform_plan(effect_name: str) -> dict[str, object]:
    return {
        "media_kind": "image",
        "transform_key": "grow_default_still",
        "effect_name": effect_name,
        "fallback_effect_name": "Transform",
        "start_scale": 100.0,
        "end_scale": 105.0,
        "reason": "default still-image transform when no optimizer plan is available",
    }


def _derive_transform_plan_from_report_entry(
    entry: dict[str, object],
    *,
    entry_index: int,
) -> dict[str, object] | None:
    candidate = entry.get("candidate")
    if not isinstance(candidate, dict):
        return None
    clip = candidate.get("clip")
    if not isinstance(clip, dict):
        return None
    media_identity = str(clip.get("source_path") or clip.get("name") or "")
    if not is_supported_image_media_path(media_identity):
        return None

    people_count = _int_value(candidate.get("people_count"), fallback=0)
    shot_scale = _int_value(candidate.get("shot_scale"), fallback=1)
    energy_level = _int_value(candidate.get("energy_level"), fallback=1)
    scene_text = _scene_text_from_candidate(candidate)

    if people_count == 0 and shot_scale == 1 and energy_level == 0 and not scene_text.strip():
        return _pattern_transform_plan(entry_index)

    if people_count >= 3:
        return {
            "media_kind": "image",
            "transform_key": "shrink_group_photo",
            "effect_name": "Shrink",
            "fallback_effect_name": "Transform",
            "start_scale": 108.0,
            "end_scale": 100.0,
            "reason": "group still image should gently pull back so faces and context remain readable",
        }
    if shot_scale >= 2 or people_count == 1:
        return {
            "media_kind": "image",
            "transform_key": "grow_portrait_focus",
            "effect_name": "Grow",
            "fallback_effect_name": "Transform",
            "start_scale": 100.0,
            "end_scale": 108.0,
            "reason": "portrait or close detail benefits from a slow push-in toward the subject",
        }
    if shot_scale <= 0 or _has_wide_context_signal(scene_text):
        return {
            "media_kind": "image",
            "transform_key": "shrink_establishing_view",
            "effect_name": "Shrink",
            "fallback_effect_name": "Transform",
            "start_scale": 106.0,
            "end_scale": 100.0,
            "reason": "wide contextual still image gets a gentle pull-back; Offset is manual-only",
        }
    if energy_level >= 2:
        return {
            "media_kind": "image",
            "transform_key": "move_energy_drift",
            "effect_name": "Move",
            "fallback_effect_name": "Transform",
            "start_scale": 103.0,
            "end_scale": 106.0,
            "reason": "higher-energy still image gets a small movement cue without using shake or spin",
        }
    return {
        "media_kind": "image",
        "transform_key": "grow_balanced_still",
        "effect_name": "Grow",
        "fallback_effect_name": "Transform",
        "start_scale": 100.0,
        "end_scale": 105.0,
        "reason": "balanced still image gets a subtle Ken Burns style push-in",
    }


def _pattern_transform_plan(entry_index: int) -> dict[str, object]:
    patterns = [
        {
            "transform_key": "grow_pattern_still",
            "effect_name": "Grow",
            "start_scale": 100.0,
            "end_scale": 105.0,
            "reason": "fallback pattern: subtle push-in for still images without scene metadata",
        },
        {
            "transform_key": "shrink_pattern_still",
            "effect_name": "Shrink",
            "start_scale": 106.0,
            "end_scale": 100.0,
            "reason": "fallback pattern: subtle pull-back for still images without scene metadata",
        },
        {
            "transform_key": "move_pattern_still",
            "effect_name": "Move",
            "start_scale": 103.0,
            "end_scale": 105.0,
            "reason": "fallback pattern: small movement cue for still images without scene metadata",
        },
    ]
    selected = dict(patterns[entry_index % len(patterns)])
    selected["media_kind"] = "image"
    selected["fallback_effect_name"] = "Transform"
    return selected


def _scene_text_from_candidate(candidate: dict[str, object]) -> str:
    assets = candidate.get("assets")
    scene_analysis: dict[str, object] = {}
    prompt_text = ""
    if isinstance(assets, dict):
        raw_scene_analysis = assets.get("scene_analysis")
        if isinstance(raw_scene_analysis, dict):
            scene_analysis = raw_scene_analysis
        prompt_text = str(assets.get("prompt_text") or "")
    parts = [
        str(scene_analysis.get("summary") or ""),
        str(scene_analysis.get("background") or ""),
        str(scene_analysis.get("shot_type") or ""),
        str(scene_analysis.get("main_action") or ""),
        " ".join(str(item) for item in (scene_analysis.get("mood") or []) if item),
        prompt_text,
    ]
    return " ".join(parts).casefold()


def _has_wide_context_signal(text: str) -> bool:
    return any(
        token in text
        for token in (
            "wide",
            "establishing",
            "landscape",
            "panorama",
            "street",
            "sea",
            "beach",
            "mountain",
            "room",
            "background",
            "outdoor",
            "city",
            "park",
        )
    )


def _clean_effect_name(value: object, *, fallback: str) -> str:
    text = str(value or "").strip()
    return text or fallback


def _int_value(value: object, *, fallback: int) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return fallback


def _float_value(value: object, *, fallback: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return fallback


def _to_js_path(path: Path) -> str:
    return str(path).replace("\\", "/")
